spring:
  application:
    name: streambox-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/streambox
    username: streambox
    password: streambox
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

server:
  port: 8080