DELETE FROM media;
ALTER SEQUENCE media_id_seq RESTART WITH 1;
INSERT INTO media (
    title,
    description,
    poster_url,
    banner_url,
    thumbnail_url,
    video_url,
    trailer_url,
    genre,
    category,
    type,
    language,
    maturity_rating,
    featured,
    rating,
    release_year,
    duration_minutes
)
VALUES
    (
        'Interstellar',
        'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.',
        'https://via.placeholder.com/300x450?text=Interstellar',
        'https://via.placeholder.com/1200x400?text=Interstellar+Banner',
        'https://via.placeholder.com/320x180?text=Interstellar+Thumb',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'https://www.youtube.com/watch?v=zSWdZVtXT7E',
        'Sci-Fi',
        'Space',
        'MOVIE',
        'English',
        'PG-13',
        true,
        8.7,
        2014,
        169
    ),
    (
        'Inception',
        'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.',
        'https://via.placeholder.com/300x450?text=Inception',
        'https://via.placeholder.com/1200x400?text=Inception+Banner',
        'https://via.placeholder.com/320x180?text=Inception+Thumb',
        'https://www.w3schools.com/html/movie.mp4',
        'https://www.youtube.com/watch?v=YoHD9XEInc0',
        'Sci-Fi',
        'Mind-Bending',
        'MOVIE',
        'English',
        'PG-13',
        true,
        8.8,
        2010,
        148
    ),
    (
        'The Dark Knight',
        'Batman sets out to dismantle the remaining criminal organizations that plague Gotham.',
        'https://via.placeholder.com/300x450?text=Dark+Knight',
        'https://via.placeholder.com/1200x400?text=Dark+Knight+Banner',
        'https://via.placeholder.com/320x180?text=Dark+Knight+Thumb',
        'https://www.w3schools.com/html/mov_bbb.mp4',
        'https://www.youtube.com/watch?v=EXeTwQWrcwY',
        'Action',
        'Superhero',
        'MOVIE',
        'English',
        'PG-13',
        false,
        9.0,
        2008,
        152
    ),
    (
        'Stranger Things',
        'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
        'https://via.placeholder.com/300x450?text=Stranger+Things',
        'https://via.placeholder.com/1200x400?text=Stranger+Things+Banner',
        'https://via.placeholder.com/320x180?text=Stranger+Things+Thumb',
        'https://www.w3schools.com/html/movie.mp4',
        'https://www.youtube.com/watch?v=b9EkMc79ZSU',
        'Sci-Fi',
        'Trending',
        'SERIES',
        'English',
        'TV-14',
        true,
        8.6,
        2016,
        51
    );